// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/node.proto

package paymentchannel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionStatus int32

const (
	ConnectionStatus_OPEN  ConnectionStatus = 0
	ConnectionStatus_CLOSE ConnectionStatus = 1
)

// Enum value maps for ConnectionStatus.
var (
	ConnectionStatus_name = map[int32]string{
		0: "OPEN",
		1: "CLOSE",
	}
	ConnectionStatus_value = map[string]int32{
		"OPEN":  0,
		"CLOSE": 1,
	}
)

func (x ConnectionStatus) Enum() *ConnectionStatus {
	p := new(ConnectionStatus)
	*p = x
	return p
}

func (x ConnectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[0].Descriptor()
}

func (ConnectionStatus) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[0]
}

func (x ConnectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionStatus.Descriptor instead.
func (ConnectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type RegisterStatus int32

const (
	RegisterStatus_ACCEPTED RegisterStatus = 0
	RegisterStatus_PENDING  RegisterStatus = 1
	RegisterStatus_REJECTED RegisterStatus = 2
)

// Enum value maps for RegisterStatus.
var (
	RegisterStatus_name = map[int32]string{
		0: "ACCEPTED",
		1: "PENDING",
		2: "REJECTED",
	}
	RegisterStatus_value = map[string]int32{
		"ACCEPTED": 0,
		"PENDING":  1,
		"REJECTED": 2,
	}
)

func (x RegisterStatus) Enum() *RegisterStatus {
	p := new(RegisterStatus)
	*p = x
	return p
}

func (x RegisterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[1].Descriptor()
}

func (RegisterStatus) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[1]
}

func (x RegisterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterStatus.Descriptor instead.
func (RegisterStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

type MsgType int32

const (
	MsgType_ERROR               MsgType = 0
	MsgType_CONFIRM_OPENCHANNEL MsgType = 1
	MsgType_RESPONSEDATA        MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "ERROR",
		1: "CONFIRM_OPENCHANNEL",
		2: "RESPONSEDATA",
	}
	MsgType_value = map[string]int32{
		"ERROR":               0,
		"CONFIRM_OPENCHANNEL": 1,
		"RESPONSEDATA":        2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[2].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[2]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MsgType `protobuf:"varint,1,opt,name=Type,proto3,enum=node.MsgType" json:"Type,omitempty"`
	Data []byte  `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_ERROR
}

func (x *Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd  string           `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgRequest) Reset() {
	*x = MsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRequest) ProtoMessage() {}

func (x *MsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRequest.ProtoReflect.Descriptor instead.
func (*MsgRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *MsgRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *MsgRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type MsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgResponse) Reset() {
	*x = MsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResponse) ProtoMessage() {}

func (x *MsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResponse.ProtoReflect.Descriptor instead.
func (*MsgResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *MsgResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MsgResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type MsgReqOpenChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      string `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	PartA_Addr   string `protobuf:"bytes,2,opt,name=PartA_Addr,json=PartAAddr,proto3" json:"PartA_Addr,omitempty"`
	PartB_Addr   string `protobuf:"bytes,3,opt,name=PartB_Addr,json=PartBAddr,proto3" json:"PartB_Addr,omitempty"`
	PubkeyA      string `protobuf:"bytes,4,opt,name=PubkeyA,proto3" json:"PubkeyA,omitempty"`
	Deposit_Amt  uint64 `protobuf:"varint,5,opt,name=Deposit_Amt,json=DepositAmt,proto3" json:"Deposit_Amt,omitempty"`
	Denom        string `protobuf:"bytes,6,opt,name=Denom,proto3" json:"Denom,omitempty"`
	Hashcode     string `protobuf:"bytes,7,opt,name=Hashcode,proto3" json:"Hashcode,omitempty"`
	PeerNodeAddr string `protobuf:"bytes,8,opt,name=peerNodeAddr,proto3" json:"peerNodeAddr,omitempty"` // IP:port
	FirstSend    uint64 `protobuf:"varint,9,opt,name=FirstSend,proto3" json:"FirstSend,omitempty"`
	FirstRecv    uint64 `protobuf:"varint,10,opt,name=FirstRecv,proto3" json:"FirstRecv,omitempty"`
}

func (x *MsgReqOpenChannel) Reset() {
	*x = MsgReqOpenChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgReqOpenChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReqOpenChannel) ProtoMessage() {}

func (x *MsgReqOpenChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReqOpenChannel.ProtoReflect.Descriptor instead.
func (*MsgReqOpenChannel) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *MsgReqOpenChannel) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MsgReqOpenChannel) GetPartA_Addr() string {
	if x != nil {
		return x.PartA_Addr
	}
	return ""
}

func (x *MsgReqOpenChannel) GetPartB_Addr() string {
	if x != nil {
		return x.PartB_Addr
	}
	return ""
}

func (x *MsgReqOpenChannel) GetPubkeyA() string {
	if x != nil {
		return x.PubkeyA
	}
	return ""
}

func (x *MsgReqOpenChannel) GetDeposit_Amt() uint64 {
	if x != nil {
		return x.Deposit_Amt
	}
	return 0
}

func (x *MsgReqOpenChannel) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgReqOpenChannel) GetHashcode() string {
	if x != nil {
		return x.Hashcode
	}
	return ""
}

func (x *MsgReqOpenChannel) GetPeerNodeAddr() string {
	if x != nil {
		return x.PeerNodeAddr
	}
	return ""
}

func (x *MsgReqOpenChannel) GetFirstSend() uint64 {
	if x != nil {
		return x.FirstSend
	}
	return 0
}

func (x *MsgReqOpenChannel) GetFirstRecv() uint64 {
	if x != nil {
		return x.FirstRecv
	}
	return 0
}

type MsgResOpenChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey         string `protobuf:"bytes,1,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Deposit_Amt    uint64 `protobuf:"varint,2,opt,name=Deposit_Amt,json=DepositAmt,proto3" json:"Deposit_Amt,omitempty"`
	Denom          string `protobuf:"bytes,3,opt,name=Denom,proto3" json:"Denom,omitempty"`
	Hashcode       string `protobuf:"bytes,4,opt,name=Hashcode,proto3" json:"Hashcode,omitempty"`
	Commitment_Sig string `protobuf:"bytes,5,opt,name=Commitment_Sig,json=CommitmentSig,proto3" json:"Commitment_Sig,omitempty"`
}

func (x *MsgResOpenChannel) Reset() {
	*x = MsgResOpenChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_node_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgResOpenChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResOpenChannel) ProtoMessage() {}

func (x *MsgResOpenChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResOpenChannel.ProtoReflect.Descriptor instead.
func (*MsgResOpenChannel) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *MsgResOpenChannel) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *MsgResOpenChannel) GetDeposit_Amt() uint64 {
	if x != nil {
		return x.Deposit_Amt
	}
	return 0
}

func (x *MsgResOpenChannel) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgResOpenChannel) GetHashcode() string {
	if x != nil {
		return x.Hashcode
	}
	return ""
}

func (x *MsgResOpenChannel) GetCommitment_Sig() string {
	if x != nil {
		return x.Commitment_Sig
	}
	return ""
}

var File_proto_node_proto protoreflect.FileDescriptor

var file_proto_node_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x6d, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x4e, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xb8, 0x02, 0x0a, 0x11, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x4f, 0x70, 0x65, 0x6e,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x74, 0x41, 0x5f, 0x41, 0x64, 0x64, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x41, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x74, 0x42, 0x5f, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x42, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x41, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x41, 0x12, 0x1f, 0x0a, 0x0b, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x5f, 0x41, 0x6d, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65,
	0x6e, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x44, 0x65, 0x6e, 0x6f, 0x6d,
	0x12, 0x1a, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x48, 0x61, 0x73, 0x68, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x70, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x70, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x63, 0x76, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x63, 0x76, 0x22, 0xa5, 0x01, 0x0a,
	0x11, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x5f, 0x41, 0x6d, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x44,
	0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x44, 0x65, 0x6e, 0x6f,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x48, 0x61, 0x73, 0x68, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x53, 0x69, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x67, 0x2a, 0x27, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x01, 0x2a, 0x39, 0x0a,
	0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0c, 0x0a, 0x08, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45,
	0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x3f, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x17,
	0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x45, 0x44, 0x41, 0x54, 0x41, 0x10, 0x02, 0x32, 0xa8, 0x01, 0x0a, 0x04, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x48, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x17, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x1a, 0x17, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x4f,
	0x70, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x12,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x09, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x09, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x0a, 0x4f, 0x70,
	0x65, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x09, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e,
	0x4d, 0x73, 0x67, 0x1a, 0x09, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x6e, 0x67, 0x74, 0x74, 0x2d, 0x61, 0x73, 0x74, 0x72, 0x61, 0x2f,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData = file_proto_node_proto_rawDesc
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_node_proto_rawDescData)
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_node_proto_goTypes = []interface{}{
	(ConnectionStatus)(0),     // 0: node.ConnectionStatus
	(RegisterStatus)(0),       // 1: node.RegisterStatus
	(MsgType)(0),              // 2: node.MsgType
	(*Msg)(nil),               // 3: node.Msg
	(*MsgRequest)(nil),        // 4: node.MsgRequest
	(*MsgResponse)(nil),       // 5: node.MsgResponse
	(*MsgReqOpenChannel)(nil), // 6: node.MsgReqOpenChannel
	(*MsgResOpenChannel)(nil), // 7: node.MsgResOpenChannel
	(*structpb.Struct)(nil),   // 8: google.protobuf.Struct
}
var file_proto_node_proto_depIdxs = []int32{
	2, // 0: node.Msg.Type:type_name -> node.MsgType
	8, // 1: node.MsgRequest.data:type_name -> google.protobuf.Struct
	8, // 2: node.MsgResponse.data:type_name -> google.protobuf.Struct
	6, // 3: node.Node.RequestOpenChannel:input_type -> node.MsgReqOpenChannel
	3, // 4: node.Node.ConfirmOpenChannel:input_type -> node.Msg
	3, // 5: node.Node.OpenStream:input_type -> node.Msg
	7, // 6: node.Node.RequestOpenChannel:output_type -> node.MsgResOpenChannel
	3, // 7: node.Node.ConfirmOpenChannel:output_type -> node.Msg
	3, // 8: node.Node.OpenStream:output_type -> node.Msg
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgReqOpenChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_node_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgResOpenChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_node_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		EnumInfos:         file_proto_node_proto_enumTypes,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_rawDesc = nil
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
